### PR TITLE
[Clean-up] Remove references to `terminusdb`

### LINKED ISSUE #513: Remove obsolete code, env vars, container related to TerminusDB
#### Tasks

- [x] Remove code specific to [TerminusDB](https://terminusdb.com/) (can move to long-lived branch if want to preserve)
- [x] Remove environment variables specific to TerminusDB
- [ ] Delete those environment variables from deployments (@eecavanna can help with this on Rancher, given the list of environment variables)
- [ ] Remove `terminus` service ("container") from development stack

#### Examples

This is not an exhaustive list.

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/api/db/terminus.py#L10

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/graphs.py#L91

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/resources.py#L517

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/terminusdb#L3

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/terminusdb/generate.py#L84

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/terminusdb/.TDB#L1

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/nmdc_runtime/site/entrypoint-dagit.sh#L24

https://github.com/microbiomedata/nmdc-runtime/blob/fb9131649f0d6ab70e7b1f105b569837afa63d17/docker-compose.yml#L91-L104

etc.

Suggestion: Use GitHub's search feature to search the repo for `TERMINUS`.

### PR DESCRIPTION
**Pull request by PeopleMakeCulture**
# Description
Removes references to terminusdb service not in use.

Fixes #513

## Type of change
Clean-up

# How Has This Been Tested?
None except CI Pipeline

- [X] My code follows the style guidelines of this project (have you run `black nmdc_runtime/`?)
- [X] I have performed a self-review of my code
- [X] I have made corresponding changes to the documentation (in `docs/` and in <https://github.com/microbiomedata/NMDC_documentation/>?)

### CODE REVIEW

**Comment by eecavanna** [comment]
This is the most aesthetically pleasing commit list I have ever seen! 📐 

image

**Comment by PeopleMakeCulture** [comment]
Tests are failing. Do the tests expect terminusDB?

**Comment by eecavanna** [comment]
Thanks, @PeopleMakeCulture. I am looking at the [recent runs](https://github.com/microbiomedata/nmdc-runtime/actions) of the failing workflow.

image

It passed when it was run on the latest commit on `main` (which happened yesterday). But all the runs after that have failed.

image

As an experiment, I will re-run it on the tip of the `main` branch. I'll report back with the result.

**Comment by eecavanna** [comment]
Oops—my bad! The failures on the https://github.com/microbiomedata/nmdc-runtime/tree/523-queries-run-cmd-response-not-ok are pytest failures (within the same workflow), not failures to connect to the FastAPI container.

**Comment by eecavanna** [comment]
I got a clue by checking this branch out locally and running `$ make up-dev`. When the `fastapi` container started up, its logs showed this error:

```py
2024-05-30 16:27:06 INFO:     Will watch for changes in these directories: ['/code']
2024-05-30 16:27:06 INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-05-30 16:27:06 INFO:     Started reloader process [1] using WatchFiles
2024-05-30 16:27:14 Process SpawnProcess-1:
2024-05-30 16:27:14 Traceback (most recent call last):
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-05-30 16:27:14     self.run()
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-05-30 16:27:14     self._target(*self._args, **self._kwargs)
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
2024-05-30 16:27:14     target(sockets=sockets)
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
2024-05-30 16:27:14     return asyncio.run(self.serve(sockets=sockets))
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2024-05-30 16:27:14     return loop.run_until_complete(main)
2024-05-30 16:27:14   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
2024-05-30 16:27:14     config.load()
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 458, in load
2024-05-30 16:27:14     self.loaded_app = import_from_string(self.app)
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-05-30 16:27:14     module = importlib.import_module(module_str)
2024-05-30 16:27:14   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-05-30 16:27:14     return _bootstrap._gcd_import(name[level:], package, level)
2024-05-30 16:27:14   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-05-30 16:27:14   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-05-30 16:27:14   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-05-30 16:27:14   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-05-30 16:27:14   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-05-30 16:27:14   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-05-30 16:27:14   File "/code/nmdc_runtime/api/main.py", line 29, in <module>
2024-05-30 16:27:14     from nmdc_runtime.api.endpoints import (
2024-05-30 16:27:14   File "/code/nmdc_runtime/api/endpoints/metadata.py", line 29, in <module>
2024-05-30 16:27:14     from nmdc_runtime.site.repository import repo, run_config_frozen__normal_env
2024-05-30 16:27:14   File "/code/nmdc_runtime/site/repository.py", line 27, in <module>
2024-05-30 16:27:14     from nmdc_runtime.site.graphs import (
2024-05-30 16:27:14   File "/code/nmdc_runtime/site/graphs.py", line 3, in <module>
2024-05-30 16:27:14     from nmdc_runtime.site.ops import (
2024-05-30 16:27:14 ImportError: cannot import name 'update_schema' from 'nmdc_runtime.site.ops' (/code/nmdc_runtime/site/ops.py)
```

**Comment by eecavanna** [comment]
@PeopleMakeCulture, here's a patch that fixes the error I referred to in my previous comment.

```diff
$ git diff nmdc_runtime/site/graphs.py 
diff --git a/nmdc_runtime/site/graphs.py b/nmdc_runtime/site/graphs.py
index 09c5d51..5b21ac0 100644
--- a/nmdc_runtime/site/graphs.py
+++ b/nmdc_runtime/site/graphs.py
@@ -22,7 +22,6 @@ from nmdc_runtime.site.ops import (
     hello,
     mongo_stats,
     submit_metadata_to_db,
-    update_schema,
     filter_ops_undone_expired,
     construct_jobs,
     maybe_post_jobs,
```

I don't know whether that's the same underlying problem that is affecting the GHA workflow.

**Comment by PeopleMakeCulture** [comment]
> @PeopleMakeCulture, here's a patch that fixes the `ImportError` I referred to in my previous comment.
> 
> ```diff
> $ git diff nmdc_runtime/site/graphs.py 
> diff --git a/nmdc_runtime/site/graphs.py b/nmdc_runtime/site/graphs.py
> index 09c5d51..5b21ac0 100644
> --- a/nmdc_runtime/site/graphs.py
> +++ b/nmdc_runtime/site/graphs.py
> @@ -22,7 +22,6 @@ from nmdc_runtime.site.ops import (
>      hello,
>      mongo_stats,
>      submit_metadata_to_db,
> -    update_schema,
>      filter_ops_undone_expired,
>      construct_jobs,
>      maybe_post_jobs,
> ```
> 
> I don't know whether that's the same underlying problem that is affecting the GHA workflow.

Hi @eecavanna do you have a PR with this patch?

**Comment by PeopleMakeCulture** [comment]
@eecavanna That worked! Could you review the PR and remove the terminus dependencies in rancher?

**Comment by eecavanna** [comment]
Great! I'll review the PR now.

**Comment by eecavanna** [comment]
Looks like a lot of files changed due to formatting changes only. I wonder whether this situation could be avoided in the future by running `black` on the entire codebase in a dedicated PR that is only about code formatting. Then, once that has been merged in, formatting-only changes wouldn't appear in the diffs of future PRs.

**Comment by eecavanna** [comment]
I'm having a hard time reviewing this PR. @PeopleMakeCulture, will you make a new version of this PR that doesn't have the formatting-only changes in it? I don't know how time-consuming that would be at this point. I think it can be done by `pluck`-ing each commit other than https://github.com/microbiomedata/nmdc-runtime/pull/542/commits/6f01714270963724aca54b696b2ab396fbdfd76a (the one whose commit message is `run black`) into a new branch, and then opening a PR for that branch.

**Comment by eecavanna** [comment]
I just realized `git cherry-pick` preserves the commit's original author (I had assumed it didn't). In that case, I will try to create such a branch, myself (i.e. one that lacks the `run black` commit). I'll report back after I've tried.

**Comment by eecavanna** [comment]
I created the branch I had in mind; and I opened a PR containing it. That PR is here: https://github.com/microbiomedata/nmdc-runtime/pull/549.

Then (oops), I realized I might be able to `$ git revert` that single `run black` commit from _this_ PR's branch. I tried that and confirmed the result matches the branch I created in #549. So, I'll close PR #549.

**Review by eecavanna — APPROVED** [review]
I am comfortable with this being merged in. Thanks, @PeopleMakeCulture, for implementing this!

P.S. To summarize my past few comments: I reverted the `run black` commit in an attempt to make the overall diff easier for me to read. The formatting of files unrelated to removing TerminusDB can be performed in a separate PR (that is what I prefer).

**Review by dwinston — APPROVED** [review]
great!

**Pull request merged**
