### PR TITLE
Replace deprecated `utcnow()` calls with `now(timezone.utc)`

### PR DESCRIPTION
**Pull request by shreddd**
Fix to address deprecated datetime.utcnow() calls

### CODE REVIEW

**Review by eecavanna — APPROVED** [review]
I see the deprecation notice in the [Python 3 docs](https://docs.python.org/3/library/datetime.html#datetime.datetime.now):

image

The changes in this branch are consistent with "the recommended way" shown in the red box on that page.

**Comment by eecavanna** [comment]
I confirmed that, even in the Python **3.10** docs, this replacement is "recommended."

image

The reason I checked that version of the Python docs is that that is the Python version that is running in the container image that runs the FastAPI app, according to [its Dockerfile](https://github.com/microbiomedata/nmdc-runtime/blob/2eb01b0b7a27b3fbfa148d2e6f72da5727a17b47/nmdc_runtime/fastapi.Dockerfile#L2C6-L2C31).

**Comment by eecavanna** [comment]
I'm comfortable with this branch being merged into `main` as is.

**Review by dwinston — APPROVED** [review]
Great. Thanks.

**Pull request merged**
