### PR TITLE
Implement v7.8.0 to v8.0.0 migration notebook and refactor notebook folder

### PR DESCRIPTION
**Pull request by brynnz22**
Related to issue https://github.com/microbiomedata/nmdc-schema/issues/1031 and
PR https://github.com/microbiomedata/nmdc-schema/pull/1109

I copied and pasted @eecavanna work from the previous migration and just substituted the new migration function for the `extraction_set`. 

The above PR in the `nmdc-schema` repo is the related schema change. It involves changing the slot `sample_mass` used by the `Extraction` class to `input_mass`

### CODE REVIEW

**Comment by eecavanna** [comment]
Thank you for making this, @brynnz22! I reviewed it and it looks good to me.

I have two suggestions:

The first one is to add a copy of the `.gitignore` file from the previous notebook ([link](https://github.com/microbiomedata/nmdc-runtime/blob/main/demo/metadata_migration/from_7_7_2_to_7_8_0/.gitignore)), to this folder. That would make it so Git ignores the following things: 
1. The `.notebook.env` config file created by the person preparing to use/run the notebook.
        image
1. The Mongo config files created by Python's `NamedTemporaryFile` function. They all have a prefix of `tmp`. For example:
        image
    > In the call to `NamedTemporaryFile`; I opted out of the "automatic deletion" of the files (by passing `delete=False`), in case the person using the notebook wants to examine the files if an error occurs.
1. The database dump folders created by the `mongodump` commands. Their file names all have the format, `mongodump.*.out`. For example:
        image

The second one is to rename the folder and notebook file from `from_7_8_to_NEXT` to `from_7_8_0_to_NEXT` so the "`0`-ness" of the corresponding `nmdc-schema` version number (i.e. `7.8.0`) is explicitly documented in the names.

**Comment by brynnz22** [comment]
Thanks @eecavanna I made these fixes!

**Review by eecavanna — DISMISSED** [review]
LGTM! Thanks @brynnz22!

**Comment by eecavanna** [comment]
To do before merging:
- Wait for the corresponding `nmdc-schema` changes ([link](https://github.com/microbiomedata/nmdc-schema/pull/1109)) to have its definitive version number (e.g. when it gets merged into the `main` branch of that repo)
- Replace the "`NEXT`" placeholder with that version number (in folder name, notebook file name, and function name)

**Comment by eecavanna** [comment]
The PyPI package for `nmdc-schema` version `8.0.0` is now available on [PyPI](https://pypi.org/project/nmdc-schema/). I will update the PR title accordingly.

**Comment by eecavanna** [comment]
`nmdc-schema` version `8.0.0` introduced some **additional schema changes requiring data transformation** (and accompanying transformation functions) after the transformation function in this branch was written. 

It also introduced a means by which all of the transformation functions (which are now methods of a class) could be imported into scripts (such as the notebook in this branch).

I'll connect with @brynnz22 on Slack about this PR being updated so that the notebook `import`s and calls those additional transformation functions.

**Comment by eecavanna** [comment]
I'm still actively working on this branch.

**Comment by eecavanna** [comment]
Thanks, @brynnz22, for getting this notebook started! I finished adding the calls to the remaining transformation functions and refactoring the notebook folder. I'll merge this in now.

**Pull request merged**
