### PR TITLE
Account for change in `alldocs` field name from `type` to `_type_and_ancestors`

### LINKED ISSUE #850: `/data_objects/study/{study_id}` endpoint does not return all of the data objects it used to
### **Describe the bug**

The "Find data objects for study" endpoint is not returning the same results as it was two weeks ago for study `nmdc:sty-11-aygzgv51`. It appears to only be returning raw data `dobj` records and no processed data records.

Tested using:
- Swagger UI: https://api.microbiomedata.org/docs#/find/find_data_objects_for_study_data_objects_study__study_id__get
- Going to the URL directly: https://api.microbiomedata.org/data_objects/study/nmdc%3Asty-11-aygzgv51
- Querying the URL in R: `jsonlite::fromJSON('https://api.microbiomedata.org/data_objects/study/nmdc%3Asty-11-aygzgv51')`

Last time I ran this query I was able to identify 33 biosamples with processed data `dobj` records with `data_object_type` = `GC-MS Metabolomics Results`, `Annotation Enzyme Commission`, or `Annotation KEGG Orthology`. Now there are none, and it doesn't look like other processed data types are present either.

### **To Reproduce**

1. Retrieve JSON from `https://api.microbiomedata.org/data_objects/study/nmdc%3Asty-11-aygzgv51`
2. Search for records with `data_object_type` = `GC-MS Metabolomics Results`, `Annotation Enzyme Commission`, or `Annotation KEGG Orthology`
3. They are not there :(

### **Expected behavior**

I expected to see processed data records for this study as well as raw data records.

### **Acceptance Criteria**

- The "Find data objects for study" endpoint returns processed data records
- Specifically, it returns 33 biosamples with processed data records with the types listed above for  `nmdc:sty-11-aygzgv51`

### **See also**
https://github.com/microbiomedata/nmdc-runtime/issues/723
@aclum @sujaypatil96

### PR DESCRIPTION
**Pull request by sujaypatil96**
In this PR we are updating the logic for the `/data_objects/study/{study_id}` endpoint to use the newly renamed field name in `alldocs` called `_type_and_ancestors` (which previously used to be called `type`).

### Details

...

### Related issue(s)

Fixes #850 

### Related subsystem(s)

- [x] Runtime API (except the Minter)
- [ ] Minter
- [ ] Dagster
- [ ] Project documentation (in the `docs` directory)
- [ ] Translators (metadata ingest pipelines)
- [ ] MongoDB migrations
- [ ] Other

### Testing

- [x] I tested these changes (explain below)
- [ ] I did not test these changes

I tested these changes by...

### Documentation

- [ ] I **have not checked** for relevant documentation yet (e.g. in the `docs` directory)
- [ ] I have **updated** all relevant documentation so it will remain accurate
- [ ] Other (explain below)

### Maintainability

- [ ] Every Python function I defined includes a docstring _(test functions are exempt from this)_
- [ ] Every Python function parameter I introduced includes a type hint (e.g. `study_id: str`)
- [ ] All "to do" or "fix me" Python comments I added begin with either `# TODO` or `# FIXME`
- [x] I used `black` to format all the Python files I created/modified
- [ ] The PR title is in the imperative mood (e.g. "Do X") and not the declarative mood (e.g. "Does X" or "Did X")

### CODE REVIEW

**Comment by aclum** [comment]
I would like to see this accompanied by a test to guard against future changes. https://github.com/microbiomedata/nmdc-runtime/pull/817 appears to the PR that introduced this problem where I would have expected a failed test.  I did see that @eecavanna made some comments recently https://github.com/microbiomedata/nmdc-runtime/issues/725

Also since the endpoint is not working as expected we should discuss if this should be a hotfix. I would prefer this instead of waiting until the next monthly release cc @pkalita-lbl @shreddd

**Comment by shreddd** [comment]
@sujaypatil96 - can you add a test to ensure that we have a way to verify that the endpoint is working moving forward?

**Comment by shreddd** [comment]
NVM - I see the testing being addressed in #725

**Comment by eecavanna** [comment]
In case y'all want to merge in the tests I have written already (they are in branch [725](https://github.com/microbiomedata/nmdc-runtime/tree/725-core-functionality-of-data_objectsstudystudy_id-endpoint-is-not-being-tested), which is part of draft PR [849](https://github.com/microbiomedata/nmdc-runtime/pull/849)) and build on top of those in this branch, that would be OK with me. One way you could do that is by editing PR 849 so that its "base branch" is this `issue-850` one, instead of `main`.

**Review by dwinston — APPROVED** [review]
merging to update base of #849

**Comment by eecavanna** [comment]
Side note: My git client is not showing the original branch (`issue-850`) as having been merged into `main`; yet it does show that commit (410856f) as having been merged into main.

Hi @dwinston, did you by any chance merge these changes in with a "squash" commit locally?

**Pull request merged**
