### PR TITLE
Add ingest pipeline with GOLD API source

### PR DESCRIPTION
**Pull request by pkalita-lbl**
The goal of these changes is to establish patterns for brining data from external sources via the Dagster infrastructure. To this point a lot of that work has been done in a [separate repo](https://github.com/microbiomedata/sample-annotator), and a lot of it has been focused on accessing data from GOLD. These changes add classes for accessing data from the GOLD API (`GoldApiClient`) and transforming it into NMDC schema-compliant objects (`GoldTranslator`). It also wraps calls to those classes in Dagster `@op`s and `@graph`s.

### CODE REVIEW

**Comment by pkalita-lbl** [comment]
@dwinston I think this work is at a decent stable place now. Please let me know if you'd like me to go over with you in more detail or if you have other questions, comments, concerns!

**Comment by pkalita-lbl** [comment]
@dwinston @elais possible to get this reviewed in the near future?

**Comment by dwinston** [comment]
I'll plan to review this later today.

**Review by dwinston — CHANGES_REQUESTED** [review]
Ensure that at least the tests in your new modules pass via e.g.
```
make up-test
make test-build
make test-dbinit
docker compose --file docker-compose.test.yml run test -k 'test_gold_'
```

I see a failed test:
```
tests/test_data/test_gold_translator.py:443: AssertionError
```

Once this is done, let's schedule an hour for a comprehensive review. I will need some guidance, as there are many new additions.

**Comment by pkalita-lbl** [comment]
@dwinston 

* Fixed test failure.
* Updated the name of a few ops to make them less ambiguous.
* Added a few new ops to decompose operations like converting NMDC schema objects to dicts (necessary for JSON serialization) and generating export filenames. This actually removed the need to have ops with multiple outputs.
* The `get_gold_study_pipeline_inputs` op now returns a string instead of a dict. If more shared config needs to be added later, this will be a good place to use multiple outputs.
* Added input and output typing information to all ops.

**Review by dwinston — APPROVED** [review]
good.

**Pull request merged**
