### PR TITLE
Materialize mongo alldocs collection

### LINKED ISSUE #543: Materialize a version of `all_docs` collection in dev mongodb
@sujaypatil96 Could you describe the use case you had in mind?

### PR DESCRIPTION
**Pull request by dwinston**
# Description

Fixes #543 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?
- Tested manually in local instance of dagster
image

- added test_materialize_all_docs()

**Configuration Details**: none

# Checklist:

- [x] My code follows the style guidelines of this project (have you run `black nmdc_runtime/`?)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (in `docs/` and in <https://github.com/microbiomedata/NMDC_documentation/>?)
- [x] I have added tests that prove my fix is effective or that my feature works, incl. considering downstream usage (e.g. <https://github.com/microbiomedata/notebook_hackathons>) if applicable.
- [x] New and existing unit and functional tests pass locally with my changes (`make up-test && make test-run`)

### CODE REVIEW

**Comment by PeopleMakeCulture** [comment]
TODO:
- [ ] standardize `alldocs` vs `all_docs` usage
- [ ] update documentation in notebook
- [ ] consider refactoring to use [op.py](https://github.com/microbiomedata/nmdc-runtime/blob/809951694db455cd74247d00ff5b89afc577bf26/nmdc_runtime/site/ops.py#L945) code and utils

**Comment by sujaypatil96** [comment]
It looks like there are a couple of merge conflicts that need to be resolved on a couple of files in this PR, would you like to resolve them @PeopleMakeCulture, or should I do it? they seem fairly trivial so I'm happy to do it as well, do let me know.

**Comment by PeopleMakeCulture** [comment]
> It looks like there are a couple of merge conflicts that need to be resolved on a couple of files in this PR, would you like to resolve them @PeopleMakeCulture, or should I do it? they seem fairly trivial so I'm happy to do it as well, do let me know.

@sujaypatil96 Hey sorry for the delayed response. I'm still catching up from covid last week. Could you go ahead and resolve the conflicts? Happy to take a look if there's anything confusing

**Comment by PeopleMakeCulture** [comment]
Dependency versions updated via: https://github.com/microbiomedata/nmdc-runtime/pull/585

**Review by PeopleMakeCulture — APPROVED** [review]

**Pull request merged**
