### PR TITLE
Bump `nmdc-schema` from `11.0.3` to `11.1.0` and sync transitive dependencies

### LINKED ISSUE #768: Bump `nmdc-schema` from v11.0.3 to v11.1.0
- [x] Update `main.in` so it references `nmdc-schema==11.1.0`
- [x] Run `make update-deps` (something like that)

### PR DESCRIPTION
**Pull request by eecavanna**
In this branch, I bumped the `nmdc-schema` package dependency from version `11.0.3` to version `11.1.0` in preparation for next week's release.

### Details

I also (effectively) ran `$ make update-deps` to synchronize the transient dependencies with the above change.

Note: Technically, I ran the following, container-based command in an attempt to further decouple the process from my host machine:

```shell
docker compose run --rm -it --name nmdc-runtime-builder fastapi sh -c 'make update-deps'
```

### Related issue(s)

Fixes #768 

### Related subsystem(s)

- [ ] Runtime API (except the Minter)
- [ ] Minter
- [ ] Dagster
- [ ] Project documentation (in the `docs` directory)
- [ ] MongoDB migrations
- [x] Other

The subsystem is: Dependencies

### Testing

- [ ] I tested these changes (explain below)
- [x] I did not test these changes

I'll leave that to GitHub Actions.

### Documentation

- [x] I **have not checked** for relevant documentation yet (e.g. in the `docs` directory)
- [ ] I have **updated** all relevant documentation so it will remain accurate
- [ ] Other (explain below)

I am assuming there is no documentation in `nmdc-runtime` that will be any less accurate with respect to `11.1.0` than with respect to `11.0.3`.

### Maintainability

- [x] Every Python function I defined includes a docstring _(test functions are exempt from this)_
- [x] Every Python function parameter I introduced includes a type hint (e.g. `study_id: str`)
- [x] All "to do" or "fix me" Python comments I added begin with either `# TODO` or `# FIXME`
- [ ] I used `black` to format all the Python files I created/modified
- [x] The PR title is in the imperative mood (e.g. "Do X") and not the declarative mood (e.g. "Does X" or "Did X")

### CODE REVIEW

**Review by aclum — APPROVED** [review]

**Comment by eecavanna** [comment]
One of the automated tests failed. The GitHub Actions workflow [log](https://github.com/microbiomedata/nmdc-runtime/actions/runs/11826756479/job/32953484398?pr=770) shows the following (this is an excerpt).

```shell
tests/test_ops/test_ops.py F                                             [ 92%]
```

```shell
================================== FAILURES ===================================
_______________ test_apply_metadata_in_functional_annotation_agg _______________

op_context = <dagster._core.execution.context.invocation.DirectOpExecutionContext object at 0x7f6be705f940>

    def test_apply_metadata_in_functional_annotation_agg(op_context):
        mongo = op_context.resources.mongo
        docs = {
            "functional_annotation_agg": [
                {
                    "metagenome_annotation_id": "nmdc:wfmtan-13-hemh0a82.1",
                    "gene_function_id": "KEGG.ORTHOLOGY:K00005",
                    "count": 10,
                    "type": "nmdc:FunctionalAnnotationAggMember",
                },
                {
                    "metagenome_annotation_id": "nmdc:wfmtan-13-hemh0a82.1",
                    "gene_function_id": "KEGG.ORTHOLOGY:K01426",
                    "count": 5,
                    "type": "nmdc:FunctionalAnnotationAggMember",
                },
            ]
        }
        # Ensure the docs are not already in the test database.
        for doc_spec in docs["functional_annotation_agg"]:
            mongo.db.functional_annotation_agg.delete_many(doc_spec)
    
        extra_run_config_data = _ensure_job__metadata_in(
            docs,
            op_context.resources.runtime_api_user_client.username,
            mongo.db,
            op_context.resources.runtime_api_site_client.client_id,
            drs_object_exists_ok=True,  # If there exists a DRS object with a matching checksum, use it.
        )
    
>       apply_metadata_in.to_job(**preset_normal).execute_in_process(
            run_config=extra_run_config_data
        )

```

I'll take a crack at fixing that.

**Comment by aclum** [comment]
tests aren't passing, we need to update one of the ops tests. I'll do that now.

**Comment by eecavanna** [comment]
@aclum I'm on it. I'm going to update the `docs` object to use the new field name. Commit incoming...

**Comment by eecavanna** [comment]
I see you took care of it. 👍 (I think we were playing "phone tag".) I expect the test to pass now. Thanks for taking care of it.

**Comment by eecavanna** [comment]
The test passed. I'll hold off on merging this in until I've done the data migration (today).

**Pull request merged**
