### PR TITLE
fix: Handle `anyOf` in JSON Schema property

### LINKED ISSUE #378: Error `KeyError: '$ref'` occurred on Dagster after using `/metadata/json:submit` endpoint
@brynnz22 submitted a JSON file to the `/metadata/json:submit` endpoint.

The corresponding run on Dagit failed:

image

Dagit shows the following error (here is a full stack trace):

```py
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "perform_mongo_updates":

  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 275, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 476, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 159, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 94, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 204, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn):
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 173, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 459, in iterate_with_context
    with context_fn():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 84, in op_execution_error_boundary
    raise error_cls(

The above exception was caused by the following exception:
KeyError: '$ref'

  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 461, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/opt/dagster/lib/nmdc_runtime/site/ops.py", line 540, in perform_mongo_updates
    docs, _ = specialize_activity_set_docs(docs)
  File "/opt/dagster/lib/nmdc_runtime/util.py", line 289, in specialize_activity_set_docs
    type_collections = get_type_collections()
  File "/opt/dagster/lib/nmdc_runtime/util.py", line 32, in get_type_collections
    return {
  File "/opt/dagster/lib/nmdc_runtime/util.py", line 33, in <dictcomp>
    f'nmdc:{spec["items"]["$ref"].split("/")[-1]}': collection_name
```

Here's what the offending line of code contains:

https://github.com/microbiomedata/nmdc-runtime/blob/1eacc43922104be514d626ac4831114f4378d2e1/nmdc_runtime/util.py#L30-L36

`nmdc_jsonschema` is defined further down the file:

https://github.com/microbiomedata/nmdc-runtime/blob/1eacc43922104be514d626ac4831114f4378d2e1/nmdc_runtime/util.py#L68

CC: @dwinston

### PR DESCRIPTION
**Pull request by eecavanna**
Fixes #378

### CODE REVIEW

**Comment by eecavanna** [comment]
I've drafted this function, but haven't tested it yet. I'm trying to get unit tests or doctests running locally.

**Comment by eecavanna** [comment]
Bug: I accidentally omitted the `nmdc:` part. Commit incoming...

**Comment by dwinston** [comment]
Grep the codebase for additional uses of “$ref” in .py files. I think there are a few other instances that we want to convert to more robust access.

**Comment by eecavanna** [comment]
I will do that and add fixes to this PR.

**Comment by eecavanna** [comment]
That's turning out to be a bit of a rabbit hole (since some things assume a 1-to-1 relationship between collections and classes). For example:

https://github.com/microbiomedata/nmdc-runtime/blob/1eacc43922104be514d626ac4831114f4378d2e1/nmdc_runtime/util.py#L315-L321

The spec for `planned_process_set` in the current NMDC Schema says...
```py
{'anyOf': [{'$ref': '#/$defs/CollectingBiosamplesFromSite'}, {'$ref': '#/$defs/BiosampleProcessing'}, {'$ref': '#/$defs/SubSamplingProcess'}, {'$ref': '#/$defs/OmicsProcessing'}, {'$ref': '#/$defs/Pooling'}, {'$ref': '#/$defs/Extraction'}, {'$ref': '#/$defs/LibraryPreparation'}]}
```

But, since this data structure is a dictionary, the key `planned_process_set` can only occur once. I could make its value a list, but that may break consuming code. I'll follow those dependency trails and see how deep they go.

**Comment by eecavanna** [comment]
Still working on this. I'm confused about what the `documentation_links` function in `find.py` is doing. I'm stepping through it.

**Comment by eecavanna** [comment]
Still in the rabbit hole. Currently in a changesheet-related function named `load_changesheet`. I have a meeting now from 3-3:30pm PT and will resume working on this after that.

**Comment by eecavanna** [comment]
@dwinston, I don't know how I can adapt this statement to work in the new "a collection can be associated with multiple classes" situation. It's within a 175-line function in the changesheet code.

https://github.com/microbiomedata/nmdc-runtime/blob/1eacc43922104be514d626ac4831114f4378d2e1/nmdc_runtime/api/core/metadata.py#L172

In this PR branch, I have arbitrarily chosen to use the first class in the list of classes. 🤷

**Comment by eecavanna** [comment]
@dwinston, I adapted this function and the associated [`search.html`](https://github.com/microbiomedata/nmdc-runtime/blob/1eacc43922104be514d626ac4831114f4378d2e1/nmdc_runtime/templates/search.html) page, to work in the new "a collection can be associated with multiple classes" situation; with the caveat that the web page will ignore any classes after the first one.

https://github.com/microbiomedata/nmdc-runtime/blob/1eacc43922104be514d626ac4831114f4378d2e1/nmdc_runtime/api/endpoints/find.py#L190-L222

**Comment by eecavanna** [comment]
Hi @dwinston, I finished making all the changes to this branch that I expect to make. I want to know what you think about what I said in these two comments:
- https://github.com/microbiomedata/nmdc-runtime/pull/379#issuecomment-1809391290
- https://github.com/microbiomedata/nmdc-runtime/pull/379#issuecomment-1809462875

I'm OK with you making additional commits to this branch.

**Comment by dwinston** [comment]
thanks for tackling this, @eecavanna. I don't love the added complexity. I'd like to try and identify a more elegant solution than this band-aid, realizing that this bug is blocking folks, so if I can't identify a better route soon, I'll go with this (after careful review). Again, thank you.

**Review by dwinston — APPROVED** [review]
I can't think of a more straightforward way to handle the appearance of one-to-many collection-to-class relationships, and I think we should shoot for straightforward for now.

**Pull request merged**
