### PR TITLE
Register dagster scheduled job to re-materialize alldocs daily

### LINKED ISSUE #809: Schedule cron job in dagster to materialize alldocs daily

### PR DESCRIPTION
**Pull request by PeopleMakeCulture**
Use MongoDB's [db.collection.renameCollection command](https://www.mongodb.com/docs/v6.0/reference/method/db.collection.renameCollection/#resource-locking-in-replica-sets) to atomically swap out `alldocs` for a re-materialized version.

@eecavanna use of `renameCollection` means we should use `mongodump --oplog` and `mongorestore --oplogReplay` with care for [microbiomedata/infra-admin](https://github.com/microbiomedata/infra-admin/blob/6bd7254b65288f6a687137b3d76b688e616cf8bb/mongodb/backups/backup_mongo.sh) (and [we should consider doing that anyway](https://www.mongodb.com/docs/database-tools/mongodump/#std-option-mongodump.--oplog)).

### Details

- Creates a new dagster ScheduleDefinition `ensure_alldocs_daily` that runs the `ensure_alldocs` graph daily at 12AM PT/3AM ET 
- Updates `apply_changesheet` and `apply_metadata_in` graphs to run `materialize_alldocs` as last step

#### TODO

(not in scope for this PR)

- ~~[ ] Updates dagster graphs for ETL jobs to run `materialize_alldocs` op as first step @sujaypatil96~~

### Related issue(s)
Closes #809 

### Related subsystem(s)

- [x] Runtime API (except the Minter)
- [ ] Minter
- [X] Dagster
- [ ] Project documentation (in the `docs` directory)
- [ ] Translators (metadata ingest pipelines)
- [x] MongoDB migrations
- [ ] Other

### Testing

- [x] I tested these changes (explain below)
- [ ] I did not test these changes

I tested these changes by manual running in Dagit.

### Documentation

- [x] I **have not checked** for relevant documentation yet (e.g. in the `docs` directory)
- [ ] I have **updated** all relevant documentation so it will remain accurate
- [ ] Other (explain below)

### Maintainability

- [x] Every Python function I defined includes a docstring _(test functions are exempt from this)_
- [x] Every Python function parameter I introduced includes a type hint (e.g. `study_id: str`)
- [x] All "to do" or "fix me" Python comments I added begin with either `# TODO` or `# FIXME`
- [x] I used `black` to format all the Python files I created/modified
- [x] The PR title is in the imperative mood (e.g. "Do X") and not the declarative mood (e.g. "Does X" or "Did X")

### CODE REVIEW

**Comment by PeopleMakeCulture** [comment]
I think there's currently a bug in the schedule definition that causes dagster to not load jobs

**Comment by dwinston** [comment]
looking and the `fastapi` service log (e.g. via `make follow-fastapi`), I see this:

```raw
dagster._core.errors.DagsterInvalidDefinitionError:
"daily materialize alldocs" is not a valid name in Dagster.
Names must be in regex ^[A-Za-z0-9_]+$.
```

**Review by dwinston — APPROVED** [review]

**Comment by dwinston** [comment]
skipping test failing on regession (see https://github.com/microbiomedata/nmdc-runtime/pull/841#issuecomment-2548553087)

**Comment by dwinston** [comment]
@eecavanna I don't want to merge prior to your review, so that I'm sure that you

- (a) are aware of implications on use of `renameCollection` for mongo backups (i.e., there is no problem unless we decide to start using `mongodump --oplog`), and
- (b) are aware of the regression introduced by #841 that I am marking as skipped for this PR.

**Review by dwinston — APPROVED** [review]

**Comment by eecavanna** [comment]
> skipping test failing on regression (see https://github.com/microbiomedata/nmdc-runtime/pull/841#issuecomment-2548553087)

Thanks for bringing this to our attention. I merged a couple PRs over the past hour or so that make the skipping unnecessary. Those PRs are:
- #846
  - Fixes bug in the changesheet
- #845
  - Configures GHA to run tests whenever that changesheet changes

For that reason, I'll remove this "skip" on this branch.

**Comment by eecavanna** [comment]
> (a) are aware of implications on use of renameCollection for mongo backups (i.e., there is no problem unless we decide to start using mongodump --oplog), and

My understanding of the implication (based on my interpretation of [the mongodump docs](https://www.mongodb.com/docs/database-tools/mongodump/#std-option-mongodump.--oplog)) is that, since we will be using `renameCollection`, if we were to do a mongodump with the `--oplog` option, that mongodump would fail if the `renameCollection` part of this Dagster job happened to run during the dumping process. I am OK with that implication.

Thanks for highlighting that implication of these changes.

**Comment by eecavanna** [comment]
> (c) are aware that a dagster scheduled job must be toggled to enable via the Dagit web UI, so there is an additional step to "deploy" this scheduled job. The toggling is persisted in dagster's internal postgresql database, so this need only be done on initial deploy to a new environment.

Thanks for bringing this to my attention. For our production environment, I see this as an additional "Release day" step, which I will add to the ticket for the next production release (i.e. ticket https://github.com/microbiomedata/issues/issues/988).

For our development environment, I will leave it to whoever merged this in to (a) enable the job via Dagit (dev) and (b) post a follow-up comment here saying they have enabled it.

**Review by eecavanna — APPROVED** [review]
LGTM! Thanks for implementing this and highlighting specific aspect of it you thought I'd want to be aware of.

**Comment by dwinston** [comment]
enabled via <https://dagit-dev.microbiomedata.org/automation>: 

image

**Comment by eecavanna** [comment]
Thanks! I have noted that task (to be done in the production environment) in the [ticket](https://github.com/microbiomedata/issues/issues/988#issuecomment-2549662469) for the next monthly NMDC Release.

**Pull request merged**
