### PR TITLE
Bump `nmdc-schema` from `10.0.0` to `10.1.0`

### PR DESCRIPTION
**Pull request by aclum**
# Description

Upping nmdc-scheam from 10.0.0 to 10.1.0 to add new file type enums for binning.

### CODE REVIEW

**Comment by eecavanna** [comment]
### TODO
- [ ] Synchronize the full dependency file with the "input" one, by running `make update-deps` within the containerized development environment
- [ ] Check whether this schema change involves any database migrations

**Comment by aclum** [comment]
@eecavanna doesn't the first item happen with the github actions? There are no migrations for 10.0.0 to 10.1.0 based on there not being a migration python script.

**Comment by eecavanna** [comment]
On my host machine, I ran the following command to attach to a bash shell running inside the `fastapi` container:
```shell
docker compose exec fastapi bash
```
In that container, I ran:
```console
# make update-deps
pip install --upgrade pip-tools pip setuptools
Requirement already satisfied: pip-tools in /usr/local/lib/python3.10/site-packages (7.3.0)
Collecting pip-tools
  Downloading pip_tools-7.4.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (23.3.2)
Collecting pip
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
(...)
```

Finally, I confirmed that the `main.txt` file contained this:
```ini
nmdc-schema==10.1.0
    # via -r requirements/main.in
```

Now, I'll commit those changes to my local copy of this branch and push them up to GitHub so they are included in this PR.

**Review by eecavanna — APPROVED** [review]

**Review by pkalita-lbl — APPROVED** [review]

**Comment by eecavanna** [comment]
Hi @aclum, I'll merge this in now. As a result, the development environment will be updated "from schema version `10.0.0` to schema version `10.1.0`.

**Pull request merged**
