### PR TITLE
Add funding source to `SubmissionPortalTranslator`

### PR DESCRIPTION
**Pull request by JamesTessmer**
# Description

This is a small PR, it changes some existing logic in `SubmissionPortalTranslator` to accommodate the inclusion of `funding_sources` since this is now collected in the submission portal.
Existing tests and documentation already include this slot as it existed in the database schema but not on the server side.

Fixes [# (issue)](https://github.com/microbiomedata/issues/issues/229)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration, if it is not simply `make up-test && make test-run`.

- [x] `test_translate_metadata_submission_to_nmdc_schema_database` in `test_submission_portal_graphs.py`
- [x] `test_submission_portal_translator.py`

Both of the above already included values for `study_funding_sources`.

**Configuration Details**: none

# Definition of Done (DoD) Checklist:
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to each feature since the definition of done is intended to be a comprehensive checklist. Consciously decide the applicability of value-added activities on a feature-by-feature basis.

- [x] My code follows the style guidelines of this project (have you run `black nmdc_runtime/`?)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (in `docs/` and in <https://github.com/microbiomedata/NMDC_documentation/>?)
- [ ] I have added tests that prove my fix is effective or that my feature works, incl. considering downstream usage (e.g. <https://github.com/microbiomedata/notebook_hackathons>) if applicable.
- [x] New and existing unit and functional tests pass locally with my changes (`make up-test && make test-run`)

### CODE REVIEW

**Comment by JamesTessmer** [comment]
@pkalita-lbl I think this is ready for review now

**Review by pkalita-lbl — APPROVED** [review]
Changes look good. 

I tested the `translate_metadata_submission_to_nmdc_schema_database` job, and it completed successfully. I also tried to test the `ingest_metadata_submission` job. It failed, but I think it was because of the changes introduced in https://github.com/microbiomedata/nmdc-runtime/pull/620. 

I think it's fine if you want to merge these changes in now, but if so we should try to remember to loop back and test `ingest_metadata_submission` once the issue introduced by https://github.com/microbiomedata/nmdc-runtime/pull/620 gets resolved.

**Comment by JamesTessmer** [comment]
It might be good to hold off for now, both for #620 and to see if Montana has any input when she returns.
I suspect she might want the text in the study form from the other PR to be multivalued since that's how `funding_sources` is represented in the mongo schema.

**Comment by pkalita-lbl** [comment]
Just an FYI that Donny has put in a fix with PR https://github.com/microbiomedata/nmdc-runtime/pull/633. If you merge `main` into this branch, we should (hopefully) be able to test the full `ingest_metadata_submission` job.

**Comment by JamesTessmer** [comment]
I've merged main back in, I'll test the `ingest_metadata_submission` job and see what happens.

**Comment by JamesTessmer** [comment]
I'm still running into some issues trying to run the job @pkalita-lbl but it looks like it might just be an issue with my config. It doesn't like how I'm defining things.

**Comment by JamesTessmer** [comment]
@pkalita-lbl Got the config issue figured out and the run completed successfully for `ingest_metadata_submission` and I tested `translate_metadata_submission_to_nmdc_schema_database` for good measure as well.

**Comment by JamesTessmer** [comment]
@pkalita-lbl I had to make a couple small changes in the runtime, and merged main back in. But everything works with the change to be multivalued.

**Review by pkalita-lbl — APPROVED** [review]
I tested both the `translate_metadata_submission_to_nmdc_schema_database` and the `ingest_metadata_submission` Dagit jobs locally and both worked!

**Pull request merged**
